default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rugnet_app_development

test:
  <<: *default
  database: rugnet_app_test

production:
  <<: *default
  database: rugnet_app_production
  username: rugnet_app
  password: <%= ENV['RUGNET_APP_DATABASE_PASSWORD'] %>
